In [1]:
import pandas as pd
import numpy as np

## `df_a와 df_b를 합치는 데이터프레임`
df_a: 매출원가감소율 2010년부터 2019년까지 있는 데이터프레임 \         
df_b: 2011년부터 2019년까지 해당산업군 중간값이 모여 있는 column\
`하려고 하는 것: df_a와 df_b의 데이터를 합치기` \
df_a의 매출원가 감소율 옆에 해당기업의 해당 년도 중간값을 찾아서 붙여주는 것

In [50]:
df_a = pd.read_csv(r"../data\전체데이터\전체데이터_1년연속부실징후기업.csv", encoding="cp949")
df_b = pd.read_csv(r"../data\회생전략\운용적.자산적 범주의 전략\직원감소율\전체데이터_2011_KOSPI+KOSDAQ_직원감소율여부.csv", encoding='cp949')
# df_a.drop(columns=["Unnamed: 0"], inplace=True)
# df_b.drop(columns=["Unnamed: 0"], inplace=True)

In [51]:
df_a

,회사명,거래소코드,회계년도,이자보상배율,총자산증가율,유형자산증가율,유동자산증가율,자기자본증가율,매출액증가율,매출액총이익율,...,재고자산_대_유동자산비율,재고자산_대_순운전자본비율,순운전자본비율,노동장비율,기계장비율,자본집약도,설비투자효율,총자본투자효율,부가가치율,종업원1인딩부가가치
0,(주)CMG제약,58820,11-Dec,3.53,1.98,-5.90,17.64,-2.02,56.40,41.83,...,17.88,35.59,28.23,71726.36,29216.43,202.26,35.85819316,12.72,19.56,25719.78
1,(주)CMG제약,58820,12-Dec,-7.75,109.15,-4.12,207.08,75.17,-8.43,28.34,...,6.27,7.33,70.60,69458.82,32002.75,426.18,0,0.47,1.66,2009.78
2,(주)CMG제약,58820,13-Dec,0.70,-2.09,16.09,-18.89,55.10,25.51,38.70,...,12.09,14.12,58.50,66012.04,33789.62,411.12,77.91470318,12.51,34.29,51433.09
3,(주)CMG제약,58820,14-Dec,3.60,3.86,74.30,-25.93,0.01,11.52,37.07,...,17.36,25.09,33.72,113899.65,48479.94,354.08,37.80253285,12.16,31.04,43056.95
4,(주)CMG제약,58820,15-Dec,-32.22,-2.64,-5.37,-7.17,-4.48,18.85,36.26,...,20.77,31.32,30.82,114246.59,53386.77,362.39,0,7.63,15.96,27662.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9121,흥아해운(주),3280,15-Dec,1.02,21.93,49.36,-11.18,3.39,2.42,6.20,...,8.43,-9.10,-15.94,593960.16,14.23,973.73,21.49400366,13.11,12.28,127665.82
9122,흥아해운(주),3280,16-Dec,0.21,21.08,38.84,-25.08,11.22,-1.58,4.49,...,17.60,-11.47,-16.34,706868.14,12.28,1017.55,15.81260955,10.98,12.66,111774.30
9123,흥아해운(주),3280,17-Dec,-0.42,-11.43,-16.50,13.29,-39.28,0.56,2.09,...,17.27,-9.61,-24.48,599097.86,12.56,921.78,8.349918093,5.43,5.51,50024.18
9124,흥아해운(주),3280,18-Dec,-1.16,-5.33,-12.07,-6.33,-37.42,-9.87,-0.93,...,17.36,-9.21,-25.40,618981.48,14.54,1009.67,0,4.24,4.52,42782.54
9125,흥아해운(주),3280,19-Dec,-0.55,-46.38,-51.51,-13.42,-57.73,-86.45,5.54,...,8.22,-7.11,-25.18,704760.75,34.13,1271.28,0,3.10,13.08,39428.47

In [10]:
df_a['회사명'] = df_a['회사명'].str.replace("(주)","")
df_a['회사명'] = df_a['회사명'].str.replace("\(","")
df_a['회사명'] = df_a['회사명'].str.replace("\)","")
df_a

C:\Users\user\AppData\Local\Temp\ipykernel_12612\4126486920.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df_a['회사명'] = df_a['회사명'].str.replace("(주)","")
C:\Users\user\AppData\Local\Temp\ipykernel_12612\4126486920.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df_a['회사명'] = df_a['회사명'].str.replace("\(","")
C:\Users\user\AppData\Local\Temp\ipykernel_12612\4126486920.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df_a['회사명'] = df_a['회사명'].str.replace("\)","")

,회사명,거래소코드,회계년도,이자보상배율,총자산증가율,유형자산증가율,유동자산증가율,자기자본증가율,매출액증가율,매출액총이익율,...,재고자산_대_순운전자본비율,순운전자본비율,노동장비율,기계장비율,자본집약도,설비투자효율,총자본투자효율,부가가치율,종업원1인딩부가가치,채울열
0,CMG제약,58820,11-Dec,3.53,1.98,-5.90,17.64,-2.02,56.40,41.83,...,35.59,28.23,71726.36,29216.43,202.26,35.85819316,12.72,19.56,25719.78,
1,CMG제약,58820,12-Dec,-7.75,109.15,-4.12,207.08,75.17,-8.43,28.34,...,7.33,70.60,69458.82,32002.75,426.18,0,0.47,1.66,2009.78,
2,CMG제약,58820,13-Dec,0.70,-2.09,16.09,-18.89,55.10,25.51,38.70,...,14.12,58.50,66012.04,33789.62,411.12,77.91470318,12.51,34.29,51433.09,
3,CMG제약,58820,14-Dec,3.60,3.86,74.30,-25.93,0.01,11.52,37.07,...,25.09,33.72,113899.65,48479.94,354.08,37.80253285,12.16,31.04,43056.95,
4,CMG제약,58820,15-Dec,-32.22,-2.64,-5.37,-7.17,-4.48,18.85,36.26,...,31.32,30.82,114246.59,53386.77,362.39,0,7.63,15.96,27662.63,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9121,흥아해운,3280,15-Dec,1.02,21.93,49.36,-11.18,3.39,2.42,6.20,...,-9.10,-15.94,593960.16,14.23,973.73,21.49400366,13.11,12.28,127665.82,
9122,흥아해운,3280,16-Dec,0.21,21.08,38.84,-25.08,11.22,-1.58,4.49,...,-11.47,-16.34,706868.14,12.28,1017.55,15.81260955,10.98,12.66,111774.30,
9123,흥아해운,3280,17-Dec,-0.42,-11.43,-16.50,13.29,-39.28,0.56,2.09,...,-9.61,-24.48,599097.86,12.56,921.78,8.349918093,5.43,5.51,50024.18,
9124,흥아해운,3280,18-Dec,-1.16,-5.33,-12.07,-6.33,-37.42,-9.87,-0.93,...,-9.21,-25.40,618981.48,14.54,1009.67,0,4.24,4.52,42782.54,
9125,흥아해운,3280,19-Dec,-0.55,-46.38,-51.51,-13.42,-57.73,-86.45,5.54,...,-7.11,-25.18,704760.75,34.13,1271.28,0,3.10,13.08,39428.47,

In [25]:
df_a["직원감소율여부"]=""
df_a=df_a.sort_values(["회사명","회계년도"])
df_a.reset_index(inplace=True,drop=True)
df_a

,회사명,거래소코드,회계년도,이자보상배율,총자산증가율,유형자산증가율,유동자산증가율,자기자본증가율,매출액증가율,매출액총이익율,...,순운전자본비율,노동장비율,기계장비율,자본집약도,설비투자효율,총자본투자효율,부가가치율,종업원1인딩부가가치,채울열,직원감소율여부
0,AJ네트웍스,95570,15-Dec,1.84,1798.61,4233.66,396.34,411.97,893.90,100.00,...,-32.71,6228677.61,47286.53,7950.23,34.17581648,26.78,43.76,2128701.43,,
1,AJ네트웍스,95570,16-Dec,1.43,20.64,14.81,36.65,7.41,18.79,100.00,...,-31.08,3922910.28,45846.41,5269.16,31.77094506,23.65,39.26,1246345.67,,
2,AJ네트웍스,95570,17-Dec,1.57,13.11,16.17,-7.68,4.61,14.13,100.00,...,-37.76,3015668.22,43073.17,3943.44,31.31632569,23.95,39.40,944396.48,,
3,AJ네트웍스,95570,18-Dec,-0.58,9.38,-86.46,373.96,9.98,-26.16,100.00,...,-3.79,480400.16,56196.71,5069.17,109.619281,10.39,25.32,526611.20,,
4,AJ네트웍스,95570,19-Dec,0.38,-29.97,11.33,-66.85,-29.37,13.83,100.00,...,-16.40,482730.51,59177.81,3395.96,173.5516971,24.67,36.99,837786.99,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9121,희림종합건축사사무소,37440,18-Dec,3.28,-0.02,8.80,-0.15,0.24,6.26,16.15,...,26.10,1833.92,3113.99,115.37,4592.906109,73.01,57.95,84230.08,,
9122,희림종합건축사사무소,37440,19-Dec,2.88,20.15,6.05,15.85,6.00,5.36,13.88,...,17.58,1880.11,3304.50,133.03,4481.829715,63.34,57.34,84263.34,,
9123,힘스,238490,17-Dec,39.32,-56.20,1167.70,-68.62,-8.83,-55.10,32.38,...,29.87,152897.09,10500.99,362.29,0,0.00,0.00,0.00,,
9124,힘스,238490,18-Dec,-3.65,-10.03,-2.11,-17.41,0.71,-61.22,28.61,...,30.92,151175.22,12223.22,329.27,0,0.00,0.00,0.00,,
9125,힘스,238490,19-Dec,68.43,33.05,6.88,54.82,15.62,139.92,33.35,...,29.84,135170.67,10568.55,378.78,0,0.00,0.00,0.00,,

In [26]:
df_b['회사명'] = df_b['회사명'].str.replace("(주)","")
df_b['회사명'] = df_b['회사명'].str.replace("\(","")
df_b['회사명'] = df_b['회사명'].str.replace("\)","")
df_b

C:\Users\user\AppData\Local\Temp\ipykernel_12612\2936247857.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df_b['회사명'] = df_b['회사명'].str.replace("(주)","")
C:\Users\user\AppData\Local\Temp\ipykernel_12612\2936247857.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df_b['회사명'] = df_b['회사명'].str.replace("\(","")
C:\Users\user\AppData\Local\Temp\ipykernel_12612\2936247857.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df_b['회사명'] = df_b['회사명'].str.replace("\)","")

             회사명   거래소코드  2011  2012  2013  2014  2015  2016  2017  2018  2019
0         AJ네트웍스   95570     0     0     0     0     0     1     1     0     0
1          CMG제약   58820     0     0     0     1     0     0     1     0     0
2          CS홀딩스     590     0     0     0     0     1     0     0     0     1
3          DB하이텍     990     0     0     0     0     0     0     0     0     0
4           ES큐브   50120     0     0     0     0     1     0     0     0     0
...          ...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
2018          흥국   10240     0     0     0     0     0     0     0     0     0
2019      흥국에프엔비  189980     0     0     0     0     0     0     0     0     0
2020        흥아해운    3280     0     0     0     0     0     0     0     0     0
2021  희림종합건축사사무소   37440     0     0     0     0     0     0     0     0     0
2022          힘스  238490     0     0     0     0     0     0     0     0     0

[2023 rows x 11 columns]

In [27]:
df_b=df_b.sort_values("회사명")
df_b.reset_index(inplace=True,drop=True)
df_b

             회사명   거래소코드  2011  2012  2013  2014  2015  2016  2017  2018  2019
0         AJ네트웍스   95570     0     0     0     0     0     1     1     0     0
1          CMG제약   58820     0     0     0     1     0     0     1     0     0
2          CS홀딩스     590     0     0     0     0     1     0     0     0     1
3          DB하이텍     990     0     0     0     0     0     0     0     0     0
4           ES큐브   50120     0     0     0     0     1     0     0     0     0
...          ...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
2018          흥국   10240     0     0     0     0     0     0     0     0     0
2019      흥국에프엔비  189980     0     0     0     0     0     0     0     0     0
2020        흥아해운    3280     0     0     0     0     0     0     0     0     0
2021  희림종합건축사사무소   37440     0     0     0     0     0     0     0     0     0
2022          힘스  238490     0     0     0     0     0     0     0     0     0

[2023 rows x 11 columns]

In [28]:
df_a[df_a['회사명']=='CMG제약']

,회사명,거래소코드,회계년도,이자보상배율,총자산증가율,유형자산증가율,유동자산증가율,자기자본증가율,매출액증가율,매출액총이익율,...,순운전자본비율,노동장비율,기계장비율,자본집약도,설비투자효율,총자본투자효율,부가가치율,종업원1인딩부가가치,채울열,직원감소율여부
5,CMG제약,58820,11-Dec,3.53,1.98,-5.90,17.64,-2.02,56.40,41.83,...,28.23,71726.36,29216.43,202.26,35.85819316,12.72,19.56,25719.78,,
6,CMG제약,58820,12-Dec,-7.75,109.15,-4.12,207.08,75.17,-8.43,28.34,...,70.60,69458.82,32002.75,426.18,0,0.47,1.66,2009.78,,
7,CMG제약,58820,13-Dec,0.70,-2.09,16.09,-18.89,55.10,25.51,38.70,...,58.50,66012.04,33789.62,411.12,77.91470318,12.51,34.29,51433.09,,
8,CMG제약,58820,14-Dec,3.60,3.86,74.30,-25.93,0.01,11.52,37.07,...,33.72,113899.65,48479.94,354.08,37.80253285,12.16,31.04,43056.95,,
9,CMG제약,58820,15-Dec,-32.22,-2.64,-5.37,-7.17,-4.48,18.85,36.26,...,30.82,114246.59,53386.77,362.39,0,7.63,15.96,27662.63,,
10,CMG제약,58820,16-Dec,303.00,96.31,-5.14,199.84,116.01,21.92,40.36,...,62.75,105508.06,53273.71,693.62,62.31075943,9.48,31.90,65742.88,,
11,CMG제약,58820,17-Dec,303.00,-1.27,-4.28,3.12,-3.13,25.98,43.43,...,64.20,80771.91,45146.70,547.84,84.86867526,12.51,33.01,68550.05,,
12,CMG제약,58820,18-Dec,303.00,4.39,6.71,0.18,6.16,20.05,45.60,...,63.71,71425.41,43924.83,515.22,106.251151,14.73,33.79,75890.32,,
13,CMG제약,58820,19-Dec,303.00,68.07,39.67,85.06,73.26,17.56,49.34,...,73.49,68915.04,44414.46,797.69,114.5992865,9.90,32.47,78976.14,,

In [29]:
len(df_a[df_a['회사명']=='CMG제약'])

9

In [30]:
df_b[df_b["회사명"]=="CMG제약"]

     회사명  거래소코드  2011  2012  2013  2014  2015  2016  2017  2018  2019
1  CMG제약  58820     0     0     0     1     0     0     1     0     0

In [31]:
df_b[df_b["회사명"]=="CMG제약"].iloc[:,10-len(df_a[df_a['회사명']=='CMG제약']):10]

   거래소코드  2011  2012  2013  2014  2015  2016  2017  2018
1  58820     0     0     0     1     0     0     1     0

In [32]:
df_b[df_b["회사명"]=="CMG제약"].iloc[:,10-len(df_a[df_a['회사명']=='CMG제약']):10].T

           1
거래소코드  58820
2011       0
2012       0
2013       0
2014       1
2015       0
2016       0
2017       1
2018       0

In [36]:
empty_df = pd.DataFrame()

In [39]:
for i in df_b["회사명"]:
    # main=df_b[df_b["구분"]==i].iloc[:,10-len(df_a[df_a['회사명']==i]):10].T.reset_index(drop=True)
    # main.columns=["col"]
    globals()["main_{}".format(i)]=df_a[df_a["회사명"]==i].reset_index(drop=True)
    globals()["side_{}".format(i)]=df_b[df_b["회사명"]==i].iloc[:,10-len(df_a[df_a['회사명']==i]):10].T.reset_index(drop=True)
    globals()["main_{}".format(i)]["채울열"]=globals()["side_{}".format(i)].iloc[:,-1]
    empty_df=empty_df.append([globals()["main_{}".format(i)]])
    # globals()["main_{}".format(i)].concat
    # side['채울열']=main["col"]
    # df_a[df_a["회사명"]==i].reset_index(drop=True)=main["col"]

SyntaxError: cannot assign to function call (2035281248.py, line 10)

In [38]:
empty_df

,회사명,거래소코드,회계년도,이자보상배율,총자산증가율,유형자산증가율,유동자산증가율,자기자본증가율,매출액증가율,매출액총이익율,...,순운전자본비율,노동장비율,기계장비율,자본집약도,설비투자효율,총자본투자효율,부가가치율,종업원1인딩부가가치,채울열,직원감소율여부
0,AJ네트웍스,95570,15-Dec,1.84,1798.61,4233.66,396.34,411.97,893.90,100.00,...,-32.71,6228677.61,47286.53,7950.23,34.17581648,26.78,43.76,2128701.43,0.0,
1,AJ네트웍스,95570,16-Dec,1.43,20.64,14.81,36.65,7.41,18.79,100.00,...,-31.08,3922910.28,45846.41,5269.16,31.77094506,23.65,39.26,1246345.67,0.0,
2,AJ네트웍스,95570,17-Dec,1.57,13.11,16.17,-7.68,4.61,14.13,100.00,...,-37.76,3015668.22,43073.17,3943.44,31.31632569,23.95,39.40,944396.48,1.0,
3,AJ네트웍스,95570,18-Dec,-0.58,9.38,-86.46,373.96,9.98,-26.16,100.00,...,-3.79,480400.16,56196.71,5069.17,109.619281,10.39,25.32,526611.20,1.0,
4,AJ네트웍스,95570,19-Dec,0.38,-29.97,11.33,-66.85,-29.37,13.83,100.00,...,-16.40,482730.51,59177.81,3395.96,173.5516971,24.67,36.99,837786.99,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,희림종합건축사사무소,37440,18-Dec,3.28,-0.02,8.80,-0.15,0.24,6.26,16.15,...,26.10,1833.92,3113.99,115.37,4592.906109,73.01,57.95,84230.08,0.0,
8,희림종합건축사사무소,37440,19-Dec,2.88,20.15,6.05,15.85,6.00,5.36,13.88,...,17.58,1880.11,3304.50,133.03,4481.829715,63.34,57.34,84263.34,0.0,
0,힘스,238490,17-Dec,39.32,-56.20,1167.70,-68.62,-8.83,-55.10,32.38,...,29.87,152897.09,10500.99,362.29,0,0.00,0.00,0.00,0.0,
1,힘스,238490,18-Dec,-3.65,-10.03,-2.11,-17.41,0.71,-61.22,28.61,...,30.92,151175.22,12223.22,329.27,0,0.00,0.00,0.00,0.0,
2,힘스,238490,19-Dec,68.43,33.05,6.88,54.82,15.62,139.92,33.35,...,29.84,135170.67,10568.55,378.78,0,0.00,0.00,0.00,0.0,

In [43]:
empty_df.drop('직원감소율여부',axis=1)

,회사명,거래소코드,회계년도,이자보상배율,총자산증가율,유형자산증가율,유동자산증가율,자기자본증가율,매출액증가율,매출액총이익율,...,재고자산_대_순운전자본비율,순운전자본비율,노동장비율,기계장비율,자본집약도,설비투자효율,총자본투자효율,부가가치율,종업원1인딩부가가치,채울열
0,AJ네트웍스,95570,15-Dec,1.84,1798.61,4233.66,396.34,411.97,893.90,100.00,...,-4.80,-32.71,6228677.61,47286.53,7950.23,34.17581648,26.78,43.76,2128701.43,0.0
1,AJ네트웍스,95570,16-Dec,1.43,20.64,14.81,36.65,7.41,18.79,100.00,...,-7.54,-31.08,3922910.28,45846.41,5269.16,31.77094506,23.65,39.26,1246345.67,0.0
2,AJ네트웍스,95570,17-Dec,1.57,13.11,16.17,-7.68,4.61,14.13,100.00,...,-6.13,-37.76,3015668.22,43073.17,3943.44,31.31632569,23.95,39.40,944396.48,1.0
3,AJ네트웍스,95570,18-Dec,-0.58,9.38,-86.46,373.96,9.98,-26.16,100.00,...,-52.66,-3.79,480400.16,56196.71,5069.17,109.619281,10.39,25.32,526611.20,1.0
4,AJ네트웍스,95570,19-Dec,0.38,-29.97,11.33,-66.85,-29.37,13.83,100.00,...,-19.82,-16.40,482730.51,59177.81,3395.96,173.5516971,24.67,36.99,837786.99,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,희림종합건축사사무소,37440,18-Dec,3.28,-0.02,8.80,-0.15,0.24,6.26,16.15,...,0.00,26.10,1833.92,3113.99,115.37,4592.906109,73.01,57.95,84230.08,0.0
8,희림종합건축사사무소,37440,19-Dec,2.88,20.15,6.05,15.85,6.00,5.36,13.88,...,0.00,17.58,1880.11,3304.50,133.03,4481.829715,63.34,57.34,84263.34,0.0
0,힘스,238490,17-Dec,39.32,-56.20,1167.70,-68.62,-8.83,-55.10,32.38,...,32.47,29.87,152897.09,10500.99,362.29,0,0.00,0.00,0.00,0.0
1,힘스,238490,18-Dec,-3.65,-10.03,-2.11,-17.41,0.71,-61.22,28.61,...,61.26,30.92,151175.22,12223.22,329.27,0,0.00,0.00,0.00,0.0
2,힘스,238490,19-Dec,68.43,33.05,6.88,54.82,15.62,139.92,33.35,...,90.39,29.84,135170.67,10568.55,378.78,0,0.00,0.00,0.00,0.0

In [48]:
empty_df.rename(columns={"채울열":"직원감소율여부"},inplace=True)
empty_df

,회사명,거래소코드,회계년도,이자보상배율,총자산증가율,유형자산증가율,유동자산증가율,자기자본증가율,매출액증가율,매출액총이익율,...,순운전자본비율,노동장비율,기계장비율,자본집약도,설비투자효율,총자본투자효율,부가가치율,종업원1인딩부가가치,직원감소율여부,직원감소율여부
0,AJ네트웍스,95570,15-Dec,1.84,1798.61,4233.66,396.34,411.97,893.90,100.00,...,-32.71,6228677.61,47286.53,7950.23,34.17581648,26.78,43.76,2128701.43,0.0,
1,AJ네트웍스,95570,16-Dec,1.43,20.64,14.81,36.65,7.41,18.79,100.00,...,-31.08,3922910.28,45846.41,5269.16,31.77094506,23.65,39.26,1246345.67,0.0,
2,AJ네트웍스,95570,17-Dec,1.57,13.11,16.17,-7.68,4.61,14.13,100.00,...,-37.76,3015668.22,43073.17,3943.44,31.31632569,23.95,39.40,944396.48,1.0,
3,AJ네트웍스,95570,18-Dec,-0.58,9.38,-86.46,373.96,9.98,-26.16,100.00,...,-3.79,480400.16,56196.71,5069.17,109.619281,10.39,25.32,526611.20,1.0,
4,AJ네트웍스,95570,19-Dec,0.38,-29.97,11.33,-66.85,-29.37,13.83,100.00,...,-16.40,482730.51,59177.81,3395.96,173.5516971,24.67,36.99,837786.99,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,희림종합건축사사무소,37440,18-Dec,3.28,-0.02,8.80,-0.15,0.24,6.26,16.15,...,26.10,1833.92,3113.99,115.37,4592.906109,73.01,57.95,84230.08,0.0,
8,희림종합건축사사무소,37440,19-Dec,2.88,20.15,6.05,15.85,6.00,5.36,13.88,...,17.58,1880.11,3304.50,133.03,4481.829715,63.34,57.34,84263.34,0.0,
0,힘스,238490,17-Dec,39.32,-56.20,1167.70,-68.62,-8.83,-55.10,32.38,...,29.87,152897.09,10500.99,362.29,0,0.00,0.00,0.00,0.0,
1,힘스,238490,18-Dec,-3.65,-10.03,-2.11,-17.41,0.71,-61.22,28.61,...,30.92,151175.22,12223.22,329.27,0,0.00,0.00,0.00,0.0,
2,힘스,238490,19-Dec,68.43,33.05,6.88,54.82,15.62,139.92,33.35,...,29.84,135170.67,10568.55,378.78,0,0.00,0.00,0.00,0.0,

In [46]:
empty_df.to_csv('data_fianl.csv',encoding='cp949')

In [26]:
df_a.reset_index(drop=True, inplace=True)
df_a = df_b["구분"]

In [27]:
df_b = df_b.iloc[:, 1:]
df_b

,2011년.mid,2012년.mid,2013년.mid,2014년.mid,2015년.mid,2016년.mid,2017년.mid,2018년.mid,2019년.mid
0,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.60
1,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.60
2,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.60
3,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.60
4,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.60
...,...,...,...,...,...,...,...,...,...
2018,0.00,0.00,0.00,0.00,0.00,44.41,46.35,52.67,51.58
2019,0.00,0.00,0.00,0.00,0.00,44.41,46.35,52.67,51.58
2020,0.00,0.00,0.00,0.00,0.00,44.41,46.35,52.67,51.58
2021,89.79,89.82,88.75,85.50,89.64,88.22,93.29,74.19,52.67
2022,32.28,33.51,33.70,33.44,31.44,34.14,33.39,34.72,35.81

In [28]:
df_a = pd.DataFrame(df_a)
df_a

                 구분
0             CMG제약
1              경보제약
2               나이벡
3               녹십자
4            녹십자엠에스
...             ...
2018    농업회사법인농우바이오
2019    농업회사법인아시아종묘
2020  우리손에프앤지농업회사법인
2021      애머릿지코퍼레이션
2022            코웨이

[2023 rows x 1 columns]

In [10]:
df_b.head(3)

     회사명  거래소코드    회계년도 매출원가감소율
0  CMG제약  58820  11-Dec  -24.14
1  CMG제약  58820  12-Dec   19.44
2  CMG제약  58820  13-Dec  -18.03

In [37]:
for i in range(0, len(df_a)):
    com_c = pd.concat([df_a.loc[i], df_b.loc[i]], axis=1)
    com_c.iloc[1, 0] = com_c.iloc[0, 0]
    com_c = com_c.iloc[1:].reset_index()
    com_c.columns = ['index', 0, 0]
    if i == 0:
        com_d = com_c
        continue
    else:
        com_d = pd.concat([com_d, com_c])

KeyError: 2023

In [12]:
df_a = pd.DataFrame(df_a["회사명"].drop_duplicates())
df_a.dropna(inplace=True)

In [14]:
df_a

        회사명
0     CMG제약
1     DB하이텍
2      ES큐브
3     HJ중공업
4     MH에탄올
...     ...
2018   휴림로봇
2019   휴마시스
2020     휴젤
2021   흥구석유
2022   흥아해운

[2023 rows x 1 columns]

In [15]:
df_a.reset_index(drop=True, inplace=True)
df_a = df_b["회사명"]

In [16]:
df_b = df_b.iloc[:, 1:]
df_b

       거래소코드    회계년도       매출원가감소율
0      58820  11-Dec        -24.14
1      58820  12-Dec         19.44
2      58820  13-Dec        -18.03
3      58820  14-Dec          3.17
4      58820  15-Dec          1.56
...      ...     ...           ...
15199   3280  15-Dec             0
15200   3280  16-Dec   2.083333333
15201   3280  17-Dec   2.040816327
15202   3280  18-Dec    2.97029703
15203   3280  19-Dec  -7.446808511

[15204 rows x 3 columns]