In [2]:
import pandas as pd

In [30]:
df = pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/재무적 범주의 전략/비유동금융부채.csv',encoding='cp949')
df

,회사,코드,년도,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,(주)CMG제약,58820,비유동금융부채(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,156757.0
1,(주)DB하이텍,990,비유동금융부채(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,831797.0,11328081.0
2,(주)ES큐브,50120,비유동금융부채(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,(주)HJ중공업,97230,비유동금융부채(*)(IFRS)(천원),16779000.0,11657000.0,8640000.0,13218000.0,36982000.0,2306000.0,4457000.0,5140000.0,182416000.0
4,(주)MH에탄올,23150,비유동금융부채(*)(IFRS)(천원),0.0,7280.0,26897.0,136245.0,79005.0,30800.0,4124.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2198,휴림로봇(주),90710,비유동금융부채(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,173770.0
2199,휴마시스(주),205470,비유동금융부채(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,0.0,3870824.0,0.0
2200,휴젤(주),145020,비유동금융부채(*)(IFRS)(천원),0.0,0.0,18200850.0,0.0,0.0,0.0,0.0,0.0,3552945.0
2201,흥구석유(주),24060,비유동금융부채(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2202,흥아해운(주),3280,비유동금융부채(*)(IFRS)(천원),695755.0,320000.0,300000.0,300000.0,300000.0,300000.0,4988380.0,327900.0,208164558.0

In [ ]:
# df.fillna(0)

In [32]:
# for i in range(1,8):
#     df['201[i]']=(df['201[i+1]']-df['201[i]'])/df['201[i]']*100
#감소율 column넣어주기

a

,회사,코드,년도,2011,2012,2013,2014,2015,2016,2017,2018,2019,2012년 감소율,2013년 감소율,2014년 감소율,2015년 감소율,2016년 감소율,2017년 감소율,2018년 감소율,2019년 감소율
0,(주)CMG제약,58820,비유동금융부채(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,156757.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-inf
1,(주)DB하이텍,990,비유동금융부채(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,831797.0,11328081.0,NaN,NaN,NaN,NaN,NaN,NaN,-inf,-1261.88
2,(주)ES큐브,50120,비유동금융부채(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)HJ중공업,97230,비유동금융부채(*)(IFRS)(천원),16779000.0,11657000.0,8640000.0,13218000.0,36982000.0,2306000.0,4457000.0,5140000.0,182416000.0,30.53,25.88,-52.99,-179.79,93.76,-93.28,-15.32,-3448.95
4,(주)MH에탄올,23150,비유동금융부채(*)(IFRS)(천원),0.0,7280.0,26897.0,136245.0,79005.0,30800.0,4124.0,0.0,0.0,-inf,-269.46,-406.54,42.01,61.02,86.61,100.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2198,휴림로봇(주),90710,비유동금융부채(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,173770.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-inf
2199,휴마시스(주),205470,비유동금융부채(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,0.0,3870824.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-inf,100.00
2200,휴젤(주),145020,비유동금융부채(*)(IFRS)(천원),0.0,0.0,18200850.0,0.0,0.0,0.0,0.0,0.0,3552945.0,NaN,-inf,100.00,NaN,NaN,NaN,NaN,-inf
2201,흥구석유(주),24060,비유동금융부채(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2202,흥아해운(주),3280,비유동금융부채(*)(IFRS)(천원),695755.0,320000.0,300000.0,300000.0,300000.0,300000.0,4988380.0,327900.0,208164558.0,54.01,6.25,0.00,0.00,0.00,-1562.79,93.43,-63384.16

In [ ]:
# -20%이상 감소하면 0,1 입력하기

for i in range(0, len(df_rate)):
    for year in range(2012, 2020):
        #print(year)
        if df_rate.iloc[i][str(year-1)+"년"] > df_rate.iloc[i][str(year-1)+"년.mid"]:
            if year != 2019:
                if ((df_rate.iloc[i][str(year)+"년"] - df_rate.iloc[i][str(year-1)+"년"]) / df_rate.iloc[i][str(year)+"년"]).round(2) < -20:
                    df_rate.loc[i, str(year)+"년비교"] = 1
                elif ((df_rate.iloc[i][str(year+1)+"년"] - df_rate.iloc[i][str(year)+"년"]) / df_rate.iloc[i][str(year+1)+"년"]).round(2) < -20:
                    df_rate.loc[i, str(year)+"년비교"] = 1
            else:
                if ((df_rate.iloc[i][str(year)+"년"] - df_rate.iloc[i][str(year-1)+"년"]) / df_rate.iloc[i][str(year)+"년"]).round(2) < -20:
                    df_rate.loc[i, str(year)+"년비교"] = 1

In [27]:
df.fillna(0)

,Unnamed: 0,구분,코드,산업명,2011년,2011년.mid,2012년,2012년.mid,2013년,2013년.mid,...,2019년,2019년.mid,2012년 감소율,2013년 감소율,2014년 감소율,2015년 감소율,2016년 감소율,2017년 감소율,2018년 감소율,2019년 감소율
0,0,(주)CMG제약,58820,의료용 물질 및 의약품 제조업,58.17,41.73,71.66,41.84,61.54,43.25,...,50.66,57.60,-23.19,14.12,-2.26,-1.29,6.43,5.15,3.84,6.88
1,1,(주)경보제약,214390,의료용 물질 및 의약품 제조업,0.00,41.73,0.00,41.84,0.00,43.25,...,78.76,57.60,0.00,0.00,0.00,-inf,-5.02,6.39,-5.64,-4.28
2,2,(주)나이벡,138610,의료용 물질 및 의약품 제조업,87.60,41.73,73.71,41.84,113.09,43.25,...,57.17,57.60,15.86,-53.43,28.50,3.96,-7.33,17.25,-32.13,37.27
3,3,(주)녹십자,6280,의료용 물질 및 의약품 제조업,65.37,41.73,67.22,41.84,68.11,43.25,...,72.98,57.60,-2.83,-1.32,2.01,0.97,-6.57,-1.36,-4.17,1.87
4,4,(주)녹십자엠에스,142280,의료용 물질 및 의약품 제조업,0.00,41.73,0.00,41.84,0.00,43.25,...,90.49,57.60,0.00,0.00,-inf,-4.69,0.01,0.84,-6.71,-0.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018,2018,농업회사법인(주)농우바이오,54050,농업,37.58,0.00,0.00,0.00,40.52,0.00,...,51.58,51.58,100.00,-inf,0.62,3.92,-14.78,-4.37,-2.35,-8.73
2019,2019,농업회사법인아시아종묘(주),154030,농업,0.00,0.00,0.00,0.00,0.00,0.00,...,50.08,51.58,0.00,0.00,0.00,0.00,0.00,0.00,-inf,4.92
2020,2020,우리손에프앤지농업회사법인(주),73560,농업,0.00,0.00,0.00,0.00,0.00,0.00,...,89.61,51.58,0.00,0.00,0.00,0.00,-inf,7.12,-10.33,0.83
2021,2021,애머릿지코퍼레이션,900100,자동차 및 부품 판매업,89.79,89.79,89.82,89.82,88.75,88.75,...,52.67,52.67,-0.03,1.19,3.66,-4.84,1.58,-5.75,20.47,29.01
2022,2022,코웨이(주),21240,기타 개인 서비스업,32.28,32.28,33.51,33.51,33.70,33.70,...,35.81,35.81,-3.81,-0.57,0.77,5.98,-8.59,2.20,-3.98,-3.14

In [ ]:
당기 = 2012년
year = 2012

for i in range(0,len(df)):
    for j in range(5,len(df_rate.columns)-6):
        if df_rate.iloc[i][j-2]<df_rate.iloc[i][j-1]:
         if df_rate[i][j]-df_rate[i][j+3]/df_rate[i][j]

In [28]:
df.to_csv('매출원가율감소여부.csv',encoding='CP949')