In [125]:
import pandas as pd
import numpy as np

## 데이터 만들기

In [140]:
df = pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/계산/매출원가율.csv',encoding='cp949')
df

,회사명,회계년도,거래소코드,매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원),매출원가율
0,CMG제약,11-Dec,58820,17751704,10325799,0.581679
1,CMG제약,12-Dec,58820,16255389,11648690,0.716605
2,CMG제약,13-Dec,58820,20402140,12506817,0.613015
3,CMG제약,14-Dec,58820,22752584,14318048,0.629293
4,CMG제약,15-Dec,58820,27041894,17237814,0.637448
...,...,...,...,...,...,...
9024,흥아해운,14-Dec,3280,825144979,778837666,0.943880
9025,흥아해운,15-Dec,3280,845115359,792690121,0.937967
9026,흥아해운,16-Dec,3280,831746081,794370084,0.955063
9027,흥아해운,17-Dec,3280,836427496,818958179,0.979114
9028,흥아해운,18-Dec,3280,753865569,760867431,1.009288

In [141]:
df['회계년도'] = pd.to_datetime(df['회계년도'],format='%d-%b').dt.strftime('20%d-%m')
df

,회사명,회계년도,거래소코드,매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원),매출원가율
0,CMG제약,2011-12,58820,17751704,10325799,0.581679
1,CMG제약,2012-12,58820,16255389,11648690,0.716605
2,CMG제약,2013-12,58820,20402140,12506817,0.613015
3,CMG제약,2014-12,58820,22752584,14318048,0.629293
4,CMG제약,2015-12,58820,27041894,17237814,0.637448
...,...,...,...,...,...,...
9024,흥아해운,2014-12,3280,825144979,778837666,0.943880
9025,흥아해운,2015-12,3280,845115359,792690121,0.937967
9026,흥아해운,2016-12,3280,831746081,794370084,0.955063
9027,흥아해운,2017-12,3280,836427496,818958179,0.979114
9028,흥아해운,2018-12,3280,753865569,760867431,1.009288

In [6]:
df.isna().sum()

Unnamed: 0                  0
회사명                         0
회계년도                        0
거래소코드                       0
매출액(수익)(*)(IFRS연결)(천원)      0
매출원가(*)(IFRS연결)(천원)         0
매출원가율                       3
매출원가율_                    195
매출원가감소율                   216
dtype: int64

In [41]:
# df = df.fillna(0)
# df

## 개별.연결 결측치 채우기

In [58]:
df['매출액(수익)(*)(IFRS연결)(천원)'] = df['매출액(수익)(*)(IFRS연결)(천원)'].fillna(df['매출액(수익)(*)(IFRS)(천원)'])
df['매출원가(*)(IFRS연결)(천원)'] = df['매출원가(*)(IFRS연결)(천원)'].fillna(df['매출액(수익)(*)(IFRS)(천원)'])
df.isna().sum()

회사명                         0
거래소코드                       0
회계년도                        0
매출액(수익)(*)(IFRS)(천원)      290
매출원가(*)(IFRS)(천원)         290
매출액(수익)(*)(IFRS연결)(천원)    214
매출원가(*)(IFRS연결)(천원)       214
dtype: int64

In [9]:
df

,Unnamed: 0,회사명,회계년도,거래소코드,매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원),매출원가율,매출원가율_,매출원가감소율
0,0,CMG제약,2011-12,58820,17751704,10325799,0.58,0.72,0.14
1,1,CMG제약,2012-12,58820,16255389,11648690,0.72,0.58,-0.14
2,2,CMG제약,2013-12,58820,20402140,12506817,0.61,0.72,0.11
3,3,CMG제약,2014-12,58820,22752584,14318048,0.63,0.61,-0.02
4,4,CMG제약,2015-12,58820,27041894,17237814,0.64,0.63,-0.01
...,...,...,...,...,...,...,...,...,...
9024,9024,흥아해운,2014-12,3280,825144979,778837666,0.94,0.94,0
9025,9025,흥아해운,2015-12,3280,845115359,792690121,0.94,0.94,0
9026,9026,흥아해운,2016-12,3280,831746081,794370084,0.96,0.94,-0.02
9027,9027,흥아해운,2017-12,3280,836427496,818958179,0.98,0.96,-0.02
9028,9028,흥아해운,2018-12,3280,753865569,760867431,1.01,0.98,-0.03

In [44]:
df = df.drop(['Unnamed: 0'],axis=1)

In [44]:
# # 개별 연결 합치기(매출액, 매출원가)
# for i in range(len(df)):
#     if df.loc[i,'매출액(수익)(*)(IFRS)(천원)']==np.nan:
#         df.loc[i,'매출액(수익)(*)(IFRS)(천원)']=df.loc[i,'매출액(수익)(*)(IFRS연결)(천원)']

# for i in range(len(df)):
#     if df.loc[i,'매출원가(*)(IFRS)(천원)']=="NaN":
#         df.loc[i,'매출원가(*)(IFRS)(천원)']=df.loc[i,'매출원가(*)(IFRS연결)(천원)']
# df

## 개별 column삭제 후  d1프레임 생성/ 매출원가율 column생성

In [60]:
df.drop(['매출액(수익)(*)(IFRS)(천원)'],axis=1,inplace=True)
df.drop(['매출원가(*)(IFRS)(천원)'],axis=1, inplace=True)

In [143]:
df = pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/운용적.자산적 범주의 전략/매출원가축소/전체데이터_KOSPI+KOSDAQ_매출액_매출원가.csv',encoding='cp949')
df

,회사명,거래소코드,회계년도,매출액(수익)(*)(IFRS)(천원),매출원가(*)(IFRS)(천원),매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원)
0,(주)CMG제약,58820,10-Dec,11350419.0,8217627.0,11350419.0,8217627.0
1,(주)CMG제약,58820,11-Dec,17751704.0,10325799.0,17751704.0,10325799.0
2,(주)CMG제약,58820,12-Dec,16255389.0,11648690.0,16255389.0,11648690.0
3,(주)CMG제약,58820,13-Dec,20322140.0,12506817.0,20402140.0,12506817.0
4,(주)CMG제약,58820,14-Dec,22752584.0,14318048.0,22752584.0,14318048.0
...,...,...,...,...,...,...,...
16498,흥아해운(주),3280,15-Dec,801560945.0,763642673.0,845115359.0,792690121.0
16499,흥아해운(주),3280,16-Dec,779990350.0,756984914.0,831746081.0,794370084.0
16500,흥아해운(주),3280,17-Dec,780863972.0,778062692.0,836427496.0,818958179.0
16501,흥아해운(주),3280,18-Dec,705007198.0,724528226.0,753865569.0,760867431.0
16502,흥아해운(주),3280,19-Dec,97376909.0,98752599.0,102166838.0,96504366.0

In [132]:
df = df.drop(['매출액(수익)(*)(IFRS)(천원)',''],axis=1,inplace=True)

In [46]:
# df1.to_csv("C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/운용적.자산적 범주의 전략/매출원가축소/데이터중복프레임제거.csv",encoding='CP949')

In [137]:
df['매출원가율']=(df['매출원가(*)(IFRS연결)(천원)']/df['매출액(수익)(*)(IFRS연결)(천원)'])
df

,Unnamed: 0,회사명,회계년도,거래소코드,매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원),매출원가율
0,0,CMG제약,11-Dec,58820,17751704,10325799,0.581679
1,1,CMG제약,12-Dec,58820,16255389,11648690,0.716605
2,2,CMG제약,13-Dec,58820,20402140,12506817,0.613015
3,3,CMG제약,14-Dec,58820,22752584,14318048,0.629293
4,4,CMG제약,15-Dec,58820,27041894,17237814,0.637448
...,...,...,...,...,...,...,...
9024,9024,흥아해운,14-Dec,3280,825144979,778837666,0.943880
9025,9025,흥아해운,15-Dec,3280,845115359,792690121,0.937967
9026,9026,흥아해운,16-Dec,3280,831746081,794370084,0.955063
9027,9027,흥아해운,17-Dec,3280,836427496,818958179,0.979114
9028,9028,흥아해운,18-Dec,3280,753865569,760867431,1.009288

# 회사명column으로 매출원가 감소율 구하기

In [48]:
#.shift()함수 사용 
#.where()함수 사용

In [142]:
df['매출원가율_'] = df['매출원가율'].shift().where(df.회사명.eq(df.회사명.shift()))
df['매출원가감소율']=(df['매출원가율_']-df['매출원가율'])
df

,회사명,회계년도,거래소코드,매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원),매출원가율,매출원가율_,매출원가감소율
0,CMG제약,2011-12,58820,17751704,10325799,0.581679,NaN,NaN
1,CMG제약,2012-12,58820,16255389,11648690,0.716605,0.581679,-0.134925
2,CMG제약,2013-12,58820,20402140,12506817,0.613015,0.716605,0.103590
3,CMG제약,2014-12,58820,22752584,14318048,0.629293,0.613015,-0.016278
4,CMG제약,2015-12,58820,27041894,17237814,0.637448,0.629293,-0.008155
...,...,...,...,...,...,...,...,...
9024,흥아해운,2014-12,3280,825144979,778837666,0.943880,0.938060,-0.005820
9025,흥아해운,2015-12,3280,845115359,792690121,0.937967,0.943880,0.005913
9026,흥아해운,2016-12,3280,831746081,794370084,0.955063,0.937967,-0.017096
9027,흥아해운,2017-12,3280,836427496,818958179,0.979114,0.955063,-0.024051
9028,흥아해운,2018-12,3280,753865569,760867431,1.009288,0.979114,-0.030174

In [39]:
# df = df.sort_values('회계년도')
# df = df.reset_index(drop=True)
# df = df.loc[1353:]
# df = df.sort_values(by=['회사명','회계년도'])
# df = df.reset_index(drop=True)
df = df.round(2)
df

,회사명,회계년도,거래소코드,매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원),매출원가율,매출원가율_,매출원가감소율
0,AJ네트웍스,2015-12,95570,1055580857,981321900,0.93,NaN,NaN
1,AJ네트웍스,2016-12,95570,1253876535,1192017169,0.95,0.93,-0.02
2,AJ네트웍스,2017-12,95570,1431015801,821502140,0.57,0.95,0.38
3,AJ네트웍스,2018-12,95570,1056691254,1066762174,1.01,0.57,-0.44
4,AJ네트웍스,2019-12,95570,1202793724,1184949624,0.99,1.01,0.02
...,...,...,...,...,...,...,...,...
7671,희림종합건축사사무소,2018-12,37440,169470443,142106374,0.84,0.82,-0.02
7672,희림종합건축사사무소,2019-12,37440,178561343,153776066,0.86,0.84,-0.02
7673,힘스,2017-12,238490,91425665,91425665,1.00,NaN,NaN
7674,힘스,2018-12,238490,35455311,35455311,1.00,1.00,0.00
7675,힘스,2019-12,238490,85064902,85064902,1.00,1.00,0.00

In [47]:
df.to_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/운용적.자산적 범주의 전략/전체데이터_2011_KOSP+KOSDAQ_매출원가감소율.csv',encoding='cp949',index=False)

In [63]:
df.to_csv('매출원가감소율1.csv',encoding='cp949',index=False)

In [168]:
# 회계년도 2010년도인 것 제거
df1 = df1[df1.회계년도 != '2010/12']

In [138]:
df.to_csv("매출원가율.csv",encoding='CP949')

In [183]:
import pandas as pd

In [184]:
df2 = pd.read_csv("C:/Users/user/Desktop/프로젝트2/데이터/계산/데이터중복프레임제거.csv",encoding='cp949')
df2

,Unnamed: 0,회사명,거래소코드,회계년도,매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원),매출원가율,매출원가율_,매출원가감소율
0,1,(주)CMG제약,58820,11-Dec,17751704.0,10325799.0,0.58,0.72,-24.13793103
1,2,(주)CMG제약,58820,12-Dec,16255389.0,11648690.0,0.72,0.58,19.44444444
2,3,(주)CMG제약,58820,13-Dec,20402140.0,12506817.0,0.61,0.72,-18.03278689
3,4,(주)CMG제약,58820,14-Dec,22752584.0,14318048.0,0.63,0.61,3.174603175
4,5,(주)CMG제약,58820,15-Dec,27041894.0,17237814.0,0.64,0.63,1.5625
...,...,...,...,...,...,...,...,...,...
15145,16498,흥아해운(주),3280,15-Dec,845115359.0,792690121.0,0.94,0.94,0
15146,16499,흥아해운(주),3280,16-Dec,831746081.0,794370084.0,0.96,0.94,2.083333333
15147,16500,흥아해운(주),3280,17-Dec,836427496.0,818958179.0,0.98,0.96,2.040816327
15148,16501,흥아해운(주),3280,18-Dec,753865569.0,760867431.0,1.01,0.98,2.97029703
15149,16502,흥아해운(주),3280,19-Dec,102166838.0,96504366.0,0.94,1.01,-7.446808511

In [187]:
df2.to_csv("전체데이터_KOSPI+KOSDAQ_매출원가감소율.csv",encoding='CP949')

# 산업중간값 구하기
## 1.회사명에 업종코드붙이기

In [48]:
import pandas as pd

In [65]:
df3 = pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/운용적.자산적 범주의 전략/매출원가축소/산업분류코드중간값.csv',encoding='cp949')
df3

,Unnamed: 0,구분,코드,산업명,2011년.mid,2012년.mid,2013년.mid,2014년.mid,2015년.mid,2016년.mid,2017년.mid,2018년.mid,2019년.mid
0,0,(주)CMG제약,58820,의료용 물질 및 의약품 제조업,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.60
1,1,(주)경보제약,214390,의료용 물질 및 의약품 제조업,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.60
2,2,(주)나이벡,138610,의료용 물질 및 의약품 제조업,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.60
3,3,(주)녹십자,6280,의료용 물질 및 의약품 제조업,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.60
4,4,(주)녹십자엠에스,142280,의료용 물질 및 의약품 제조업,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018,2018,농업회사법인(주)농우바이오,54050,농업,0.00,0.00,0.00,0.00,0.00,44.41,46.35,52.67,51.58
2019,2019,농업회사법인아시아종묘(주),154030,농업,0.00,0.00,0.00,0.00,0.00,44.41,46.35,52.67,51.58
2020,2020,우리손에프앤지농업회사법인(주),73560,농업,0.00,0.00,0.00,0.00,0.00,44.41,46.35,52.67,51.58
2021,2021,애머릿지코퍼레이션,900100,자동차 및 부품 판매업,89.79,89.82,88.75,85.50,89.64,88.22,93.29,74.19,52.67
2022,2022,코웨이(주),21240,기타 개인 서비스업,32.28,33.51,33.70,33.44,31.44,34.14,33.39,34.72,35.81

In [66]:
df3= df3.drop(['Unnamed: 0'],axis=1)

In [67]:
df4 = df3.transpose()

In [68]:
df4

,0,1,2,3,4,5,6,7,8,9,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
구분,(주)CMG제약,(주)경보제약,(주)나이벡,(주)녹십자,(주)녹십자엠에스,(주)녹십자웰빙,(주)대성미생물연구소,(주)대웅제약,(주)동구바이오제약,(주)레고켐바이오사이언스,...,쿠쿠홈시스(주),극동유화(주),미창석유공업(주),에쓰-오일(주),한국쉘석유(주),농업회사법인(주)농우바이오,농업회사법인아시아종묘(주),우리손에프앤지농업회사법인(주),애머릿지코퍼레이션,코웨이(주)
코드,58820,214390,138610,6280,142280,234690,36480,69620,6620,141080,...,284740,14530,3650,10950,2960,54050,154030,73560,900100,21240
산업명,의료용 물질 및 의약품 제조업,의료용 물질 및 의약품 제조업,의료용 물질 및 의약품 제조업,의료용 물질 및 의약품 제조업,의료용 물질 및 의약품 제조업,의료용 물질 및 의약품 제조업,의료용 물질 및 의약품 제조업,의료용 물질 및 의약품 제조업,의료용 물질 및 의약품 제조업,의료용 물질 및 의약품 제조업,...,임대업; 부동산 제외,"코크스, 연탄 및 석유정제품 제조업","코크스, 연탄 및 석유정제품 제조업","코크스, 연탄 및 석유정제품 제조업","코크스, 연탄 및 석유정제품 제조업",농업,농업,농업,자동차 및 부품 판매업,기타 개인 서비스업
2011년.mid,41.73,41.73,41.73,41.73,41.73,41.73,41.73,41.73,41.73,41.73,...,0.0,90.16,90.16,90.16,90.16,0.0,0.0,0.0,89.79,32.28
2012년.mid,41.84,41.84,41.84,41.84,41.84,41.84,41.84,41.84,41.84,41.84,...,0.0,88.56,88.56,88.56,88.56,0.0,0.0,0.0,89.82,33.51
2013년.mid,43.25,43.25,43.25,43.25,43.25,43.25,43.25,43.25,43.25,43.25,...,0.0,88.39,88.39,88.39,88.39,0.0,0.0,0.0,88.75,33.7
2014년.mid,44.93,44.93,44.93,44.93,44.93,44.93,44.93,44.93,44.93,44.93,...,0.0,89.145,89.145,89.145,89.145,0.0,0.0,0.0,85.5,33.44
2015년.mid,48.21,48.21,48.21,48.21,48.21,48.21,48.21,48.21,48.21,48.21,...,0.0,86.01,86.01,86.01,86.01,0.0,0.0,0.0,89.64,31.44
2016년.mid,52.51,52.51,52.51,52.51,52.51,52.51,52.51,52.51,52.51,52.51,...,0.0,84.61,84.61,84.61,84.61,44.41,44.41,44.41,88.22,34.14
2017년.mid,52.32,52.32,52.32,52.32,52.32,52.32,52.32,52.32,52.32,52.32,...,0.0,89.96,89.96,89.96,89.96,46.35,46.35,46.35,93.29,33.39
2018년.mid,54.69,54.69,54.69,54.69,54.69,54.69,54.69,54.69,54.69,54.69,...,18.04,93.22,93.22,93.22,93.22,52.67,52.67,52.67,74.19,34.72
2019년.mid,57.6,57.6,57.6,57.6,57.6,57.6,57.6,57.6,57.6,57.6,...,0.0,92.475,92.475,92.475,92.475,51.58,51.58,51.58,52.67,35.81

In [69]:
df4.to_csv("transpose.csv",encoding='cp949')

In [199]:
df3 = df3.drop_duplicates(['회사명'])
df3

            회사명   거래소코드     회계년도    산업코드                             산업명
0      (주)CMG제약   58820  2011/12   32102                의료용 물질 및 의약품 제조업
9      (주)DB하이텍     990  2011/12   32601    전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업
18      (주)ES큐브   50120  2011/12   74604                     도매 및 상품 중개업
27     (주)HJ중공업   97230  2011/12   33101                     기타 운송장비 제조업
36     (주)MH에탄올   23150  2011/12   31101                          음료 제조업
...         ...     ...      ...     ...                             ...
15112   휴림로봇(주)   90710  2011/12   32902                  기타 기계 및 장비 제조업
15121   휴마시스(주)  205470  2014/12  117201                           기타금융업
15127     휴젤(주)  145020  2015/12   32101                의료용 물질 및 의약품 제조업
15132   흥구석유(주)   24060  2011/12   74607                     도매 및 상품 중개업
15141   흥아해운(주)    3280  2011/12   85001                          수상 운송업

[2023 rows x 5 columns]

In [200]:
df3 = df3.drop(['회계년도','산업코드'],axis=1)

In [223]:
import pandas as pd

In [276]:
df2

,Unnamed: 0,회사명,거래소코드,회계년도,매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원),매출원가율,매출원가율_,매출원가감소율
0,1,(주)CMG제약,58820,11-Dec,17751704.0,10325799.0,0.58,0.72,-24.13793103
1,2,(주)CMG제약,58820,12-Dec,16255389.0,11648690.0,0.72,0.58,19.44444444
2,3,(주)CMG제약,58820,13-Dec,20402140.0,12506817.0,0.61,0.72,-18.03278689
3,4,(주)CMG제약,58820,14-Dec,22752584.0,14318048.0,0.63,0.61,3.174603175
4,5,(주)CMG제약,58820,15-Dec,27041894.0,17237814.0,0.64,0.63,1.5625
...,...,...,...,...,...,...,...,...,...
15145,16498,흥아해운(주),3280,15-Dec,845115359.0,792690121.0,0.94,0.94,0
15146,16499,흥아해운(주),3280,16-Dec,831746081.0,794370084.0,0.96,0.94,2.083333333
15147,16500,흥아해운(주),3280,17-Dec,836427496.0,818958179.0,0.98,0.96,2.040816327
15148,16501,흥아해운(주),3280,18-Dec,753865569.0,760867431.0,1.01,0.98,2.97029703
15149,16502,흥아해운(주),3280,19-Dec,102166838.0,96504366.0,0.94,1.01,-7.446808511

In [277]:
df3

            회사명   거래소코드                             산업명
0      (주)CMG제약   58820                의료용 물질 및 의약품 제조업
9      (주)DB하이텍     990    전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업
18      (주)ES큐브   50120                     도매 및 상품 중개업
27     (주)HJ중공업   97230                     기타 운송장비 제조업
36     (주)MH에탄올   23150                          음료 제조업
...         ...     ...                             ...
15112   휴림로봇(주)   90710                  기타 기계 및 장비 제조업
15121   휴마시스(주)  205470                           기타금융업
15127     휴젤(주)  145020                의료용 물질 및 의약품 제조업
15132   흥구석유(주)   24060                     도매 및 상품 중개업
15141   흥아해운(주)    3280                          수상 운송업

[2023 rows x 3 columns]

## 2.데이터프레임 합치기

In [278]:
# merge("A","B",how="left")했는데 안돼서 A.merge(B,how="left")했더니 됨!^^ 
df4 = df2.merge(df3,how="left")
df4

,Unnamed: 0,회사명,거래소코드,회계년도,매출액(수익)(*)(IFRS연결)(천원),매출원가(*)(IFRS연결)(천원),매출원가율,매출원가율_,매출원가감소율,산업명
0,1,(주)CMG제약,58820,11-Dec,17751704.0,10325799.0,0.58,0.72,-24.13793103,의료용 물질 및 의약품 제조업
1,2,(주)CMG제약,58820,12-Dec,16255389.0,11648690.0,0.72,0.58,19.44444444,의료용 물질 및 의약품 제조업
2,3,(주)CMG제약,58820,13-Dec,20402140.0,12506817.0,0.61,0.72,-18.03278689,의료용 물질 및 의약품 제조업
3,4,(주)CMG제약,58820,14-Dec,22752584.0,14318048.0,0.63,0.61,3.174603175,의료용 물질 및 의약품 제조업
4,5,(주)CMG제약,58820,15-Dec,27041894.0,17237814.0,0.64,0.63,1.5625,의료용 물질 및 의약품 제조업
...,...,...,...,...,...,...,...,...,...,...
15145,16498,흥아해운(주),3280,15-Dec,845115359.0,792690121.0,0.94,0.94,0,수상 운송업
15146,16499,흥아해운(주),3280,16-Dec,831746081.0,794370084.0,0.96,0.94,2.083333333,수상 운송업
15147,16500,흥아해운(주),3280,17-Dec,836427496.0,818958179.0,0.98,0.96,2.040816327,수상 운송업
15148,16501,흥아해운(주),3280,18-Dec,753865569.0,760867431.0,1.01,0.98,2.97029703,수상 운송업
15149,16502,흥아해운(주),3280,19-Dec,102166838.0,96504366.0,0.94,1.01,-7.446808511,수상 운송업

In [259]:
import seaborn as sns

# 산업명 별로 분류한 값 보기

In [274]:
df5 = df4.groupby(['산업명', '회계년도','회사명'])['매출원가감소율']

In [ ]:
df5.median()

In [ ]:
df5 = sns.load_dataset('df4')[['']]

In [ ]:
df_x = pd.DataFrame(df[['회사명']].groupby(df['통계청 한국표준산업분류 10차(소분류)']).agg(df['통계청 한국표준산업분류 10차(소분류)']value_counts(), df['경상개발비(천원)'].count_values()))
df_x

In [ ]:
df_groupby = df4.groupby('산업명')['회계년도=11-Dec'].agg(['median']) ## 여러 칼럼에 대한 집계
df_groupby

In [ ]:
df_x = pd.DataFrame(df[['회사명']].groupby(df['통계청 한국표준산업분류 10차(소분류)']).agg(df['통계청 한국표준산업분류 10차(소분류)']value_counts(), df['경상개발비(천원)'].count_values()))
df_x

In [ ]:
df4.to_csv('path\\file_name.csv', sep=',', na_rep='NaN')

In [247]:
df4.to_csv("C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/운용적.자산적 범주의 전략/매출원가축소/전체데이터_2011_KOSPI+KOSDAQ_매출원가감소율_중간값까지구한것.csv",encoding="CP949")

In [50]:
#결측치 0으로 대체 
df1 = df.replace('#DIV/0!',0.0001)
df1 = df.replace('#VALUE!',0.0001)

In [ ]:
#DIV/0!에러랑 #VALUE에러 차이?
#DIV/0에러는 분모에

In [66]:
# df = df['2010'].astype(float)

In [145]:
df = pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/운용적.자산적 범주의 전략/매출원가축소/전체데이터_KOSPI+KOSDAQ_매출원가감소율여부_최종데이터프레임.csv',encoding='cp949')
df

,Unnamed: 0,회사명,거래소코드,회계년도,매출원가감소율,2011년.mid,2012년.mid,2013년.mid,2014년.mid,2015년.mid,2016년.mid,2017년.mid,2018년.mid,2019년.mid
0,1,(주)CMG제약,58820,11-Dec,-24.14,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.6
1,2,(주)CMG제약,58820,12-Dec,19.44,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.6
2,3,(주)CMG제약,58820,13-Dec,-18.03,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.6
3,4,(주)CMG제약,58820,14-Dec,3.17,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.6
4,5,(주)CMG제약,58820,15-Dec,1.56,41.73,41.84,43.25,44.93,48.21,52.51,52.32,54.69,57.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15199,16498,흥아해운(주),3280,15-Dec,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15200,16499,흥아해운(주),3280,16-Dec,2.083333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15201,16500,흥아해운(주),3280,17-Dec,2.040816327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15202,16501,흥아해운(주),3280,18-Dec,2.97029703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15203,16502,흥아해운(주),3280,19-Dec,-7.446808511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
# -20%이상 감소하면 0,1 입력하기

for i in range(0, len(df)):
    for year in range(2011, 2018):
        if year != 2019:
            if df.iloc[i][str(year+1)+"년 감소율"] < -20:
                df.loc[i, str(year+1)+"년 감소율여부"] = 1
            else:
                    df.loc[i, str(year+1)+"년 감소율여부"] = 0

        # else:
        #     if df.iloc[i][str(year)+"년 감소율"] < -20:
        #         df.loc[i, str(year)+"년 감소율여부"] = 1
        #     else:
        #             df.loc[i, str(year)+"년 감소율여부"] = 0

In [35]:
df.to_csv("비금융부채감소여부.csv",encoding="CP949")

## transpose용

In [161]:
import pandas as pd

In [167]:
df6 = pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/운용적.자산적 범주의 전략/매출원가축소/전체데이터_KOSPI+KOSDAQ_매출원가감소율여부_최종데이터프레임.csv',encoding='cp949')
df6

       Unnamed: 0    회사명  거래소코드    회계년도       매출원가감소율  중간값
0               0  CMG제약  58820  11-Dec       -24.14   NaN
1               1  CMG제약  58820  12-Dec        19.44   NaN
2               2  CMG제약  58820  13-Dec       -18.03   NaN
3               3  CMG제약  58820  14-Dec         3.17   NaN
4               4  CMG제약  58820  15-Dec         1.56   NaN
...           ...    ...    ...     ...           ...  ...
15199       15199   흥아해운   3280  15-Dec             0  NaN
15200       15200   흥아해운   3280  16-Dec   2.083333333  NaN
15201       15201   흥아해운   3280  17-Dec   2.040816327  NaN
15202       15202   흥아해운   3280  18-Dec    2.97029703  NaN
15203       15203   흥아해운   3280  19-Dec  -7.446808511  NaN

[15204 rows x 6 columns]

In [168]:
df6['회계년도'] = pd.to_datetime(df6['회계년도'],format='%d-%b').dt.strftime('20%d-%b')
df6

       Unnamed: 0    회사명  거래소코드      회계년도       매출원가감소율  중간값
0               0  CMG제약  58820  2011-Dec       -24.14   NaN
1               1  CMG제약  58820  2012-Dec        19.44   NaN
2               2  CMG제약  58820  2013-Dec       -18.03   NaN
3               3  CMG제약  58820  2014-Dec         3.17   NaN
4               4  CMG제약  58820  2015-Dec         1.56   NaN
...           ...    ...    ...       ...           ...  ...
15199       15199   흥아해운   3280  2015-Dec             0  NaN
15200       15200   흥아해운   3280  2016-Dec   2.083333333  NaN
15201       15201   흥아해운   3280  2017-Dec   2.040816327  NaN
15202       15202   흥아해운   3280  2018-Dec    2.97029703  NaN
15203       15203   흥아해운   3280  2019-Dec  -7.446808511  NaN

[15204 rows x 6 columns]

In [147]:
df6= df6.drop(['Unnamed: 0'],axis=1)

In [ ]:
# df7 = df6.transpose()
# df7

In [149]:
df6['회사명'] = df6['회사명'].str.replace("(주)","")
df6['회사명'] = df6['회사명'].str.replace("\(","")
df6['회사명'] = df6['회사명'].str.replace("\)","")
df6

C:\Users\user\AppData\Local\Temp\ipykernel_16472\3442319459.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df6['회사명'] = df6['회사명'].str.replace("(주)","")
C:\Users\user\AppData\Local\Temp\ipykernel_16472\3442319459.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df6['회사명'] = df6['회사명'].str.replace("\(","")
C:\Users\user\AppData\Local\Temp\ipykernel_16472\3442319459.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df6['회사명'] = df6['회사명'].str.replace("\)","")

         회사명  거래소코드    회계년도       매출원가감소율  중간값
0      CMG제약  58820  11-Dec       -24.14   NaN
1      CMG제약  58820  12-Dec        19.44   NaN
2      CMG제약  58820  13-Dec       -18.03   NaN
3      CMG제약  58820  14-Dec         3.17   NaN
4      CMG제약  58820  15-Dec         1.56   NaN
...      ...    ...     ...           ...  ...
15199   흥아해운   3280  15-Dec             0  NaN
15200   흥아해운   3280  16-Dec   2.083333333  NaN
15201   흥아해운   3280  17-Dec   2.040816327  NaN
15202   흥아해운   3280  18-Dec    2.97029703  NaN
15203   흥아해운   3280  19-Dec  -7.446808511  NaN

[15204 rows x 5 columns]

In [92]:
df7 = df6.loc[0]

In [93]:
df8= df7.transpose()

In [150]:
df6.to_csv('전체데이터_KOSPI+KOSDAQ_매출원가감소율여부_최종데이터프레임.csv',encoding='cp949')