In [34]:
import pandas as pd

In [42]:
df = pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/재무적 범주의 전략/배당금축소/배당금축소.csv',encoding='cp949')
df

            회사명  거래소코드     회계년도  배당금(*)(IFRS)(천원)
0      (주)CMG제약  58820  2010/12               0.0
1      (주)CMG제약  58820  2011/12               0.0
2      (주)CMG제약  58820  2012/12               0.0
3      (주)CMG제약  58820  2013/12               0.0
4      (주)CMG제약  58820  2014/12               0.0
...         ...    ...      ...               ...
19487   흥아해운(주)   3280  2015/12          584594.0
19488   흥아해운(주)   3280  2016/12          632567.0
19489   흥아해운(주)   3280  2017/12               0.0
19490   흥아해운(주)   3280  2018/12               0.0
19491   흥아해운(주)   3280  2019/12               0.0

[19492 rows x 4 columns]

In [45]:
df=df.fillna(0)
df

            회사명  거래소코드     회계년도  배당금(*)(IFRS)(천원)
0      (주)CMG제약  58820  2010/12               0.0
1      (주)CMG제약  58820  2011/12               0.0
2      (주)CMG제약  58820  2012/12               0.0
3      (주)CMG제약  58820  2013/12               0.0
4      (주)CMG제약  58820  2014/12               0.0
...         ...    ...      ...               ...
19487   흥아해운(주)   3280  2015/12          751621.0
19488   흥아해운(주)   3280  2016/12          584594.0
19489   흥아해운(주)   3280  2017/12          632567.0
19490   흥아해운(주)   3280  2018/12               0.0
19491   흥아해운(주)   3280  2019/12               0.0

[19492 rows x 4 columns]

In [51]:
df['배당금(*)(IFRS)(천원)_'] = df['배당금(*)(IFRS)(천원)'].shift().where(df.회사명.eq(df.회사명.shift()))
df['배당금감소율']=(df['배당금(*)(IFRS)(천원)']-df['배당금(*)(IFRS)(천원)_'])/df['배당금(*)(IFRS)(천원)']*100
df

,회사명,거래소코드,회계년도,배당금(*)(IFRS)(천원),배당금(*)(IFRS)(천원)_,배당금감소율
0,(주)CMG제약,58820,2010/12,0.0,NaN,NaN
1,(주)CMG제약,58820,2011/12,0.0,0.0,NaN
2,(주)CMG제약,58820,2012/12,0.0,0.0,NaN
3,(주)CMG제약,58820,2013/12,0.0,0.0,NaN
4,(주)CMG제약,58820,2014/12,0.0,0.0,NaN
...,...,...,...,...,...,...
19487,흥아해운(주),3280,2015/12,751621.0,751621.0,0.000000
19488,흥아해운(주),3280,2016/12,584594.0,751621.0,-28.571453
19489,흥아해운(주),3280,2017/12,632567.0,584594.0,7.583861
19490,흥아해운(주),3280,2018/12,0.0,632567.0,-inf
19491,흥아해운(주),3280,2019/12,0.0,0.0,NaN

In [53]:
df.fillna(0)

,회사명,거래소코드,회계년도,배당금(*)(IFRS)(천원),배당금(*)(IFRS)(천원)_,배당금감소율
0,(주)CMG제약,58820,2010/12,0.0,0.0,0.000000
1,(주)CMG제약,58820,2011/12,0.0,0.0,0.000000
2,(주)CMG제약,58820,2012/12,0.0,0.0,0.000000
3,(주)CMG제약,58820,2013/12,0.0,0.0,0.000000
4,(주)CMG제약,58820,2014/12,0.0,0.0,0.000000
...,...,...,...,...,...,...
19487,흥아해운(주),3280,2015/12,751621.0,751621.0,0.000000
19488,흥아해운(주),3280,2016/12,584594.0,751621.0,-28.571453
19489,흥아해운(주),3280,2017/12,632567.0,584594.0,7.583861
19490,흥아해운(주),3280,2018/12,0.0,632567.0,-inf
19491,흥아해운(주),3280,2019/12,0.0,0.0,0.000000

In [57]:
for i in range(len(df)):
    if df.loc[i,"배당금감소율"] < -20:
        df.loc[i,"배당금감소율여부"] = 1
    else:
        df.loc[i,"배당금감소율여부"] = 0

In [58]:
df

,회사명,거래소코드,회계년도,배당금(*)(IFRS)(천원),배당금(*)(IFRS)(천원)_,배당금감소율,배당금감소율여부
0,(주)CMG제약,58820,2010/12,0.0,NaN,NaN,0.0
1,(주)CMG제약,58820,2011/12,0.0,0.0,NaN,0.0
2,(주)CMG제약,58820,2012/12,0.0,0.0,NaN,0.0
3,(주)CMG제약,58820,2013/12,0.0,0.0,NaN,0.0
4,(주)CMG제약,58820,2014/12,0.0,0.0,NaN,0.0
...,...,...,...,...,...,...,...
19487,흥아해운(주),3280,2015/12,751621.0,751621.0,0.000000,0.0
19488,흥아해운(주),3280,2016/12,584594.0,751621.0,-28.571453,1.0
19489,흥아해운(주),3280,2017/12,632567.0,584594.0,7.583861,0.0
19490,흥아해운(주),3280,2018/12,0.0,632567.0,-inf,1.0
19491,흥아해운(주),3280,2019/12,0.0,0.0,NaN,0.0

In [59]:
df.to_csv("배당금감소율여부.csv",encoding="CP949")

In [23]:
df['2012년 감소율'] = (((df['2011'] - df['2012'])/df['2011'])*100).round(2)
df['2013년 감소율'] = (((df['2012'] - df['2013'])/df['2012'])*100).round(2)
df['2014년 감소율'] = (((df['2013'] - df['2014'])/df['2013'])*100).round(2)
df['2015년 감소율'] = (((df['2014'] - df['2015'])/df['2014'])*100).round(2)
df['2016년 감소율'] = (((df['2015'] - df['2016'])/df['2015'])*100).round(2)
df['2017년 감소율'] = (((df['2016'] - df['2017'])/df['2016'])*100).round(2)
df['2018년 감소율'] = (((df['2017'] - df['2018'])/df['2017'])*100).round(2)
df['2019년 감소율'] = (((df['2018'] - df['2019'])/df['2018'])*100).round(2)
df

,회사,거래소코드,년도,2011,2012,2013,2014,2015,2016,2017,2018,2019,2012년 감소율,2013년 감소율,2014년 감소율,2015년 감소율,2016년 감소율,2017년 감소율,2018년 감소율,2019년 감소율
0,(주)CMG제약,58820,배당금(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)DB하이텍,990,배당금(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,10964000.0,10857000.0,15205000.0,NaN,NaN,NaN,NaN,NaN,-inf,0.98,-40.05
2,(주)ES큐브,50120,배당금(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)HJ중공업,97230,배당금(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)MH에탄올,23150,배당금(*)(IFRS)(천원),0.0,0.0,0.0,1475705.0,1819632.0,2162558.0,2415000.0,2347984.0,2277984.0,NaN,NaN,-inf,-23.31,-18.85,-11.67,2.77,2.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2198,휴림로봇(주),90710,배당금(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2199,휴마시스(주),205470,배당금(*)(IFRS)(천원),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2200,휴젤(주),145020,배당금(*)(IFRS)(천원),0.0,0.0,1280.0,1280.0,0.0,0.0,0.0,0.0,0.0,NaN,-inf,0.00,100.00,NaN,NaN,NaN,NaN
2201,흥구석유(주),24060,배당금(*)(IFRS)(천원),727041.0,436225.0,436225.0,727041.0,1163265.0,1454082.0,1454082.0,1744898.0,2181122.0,40.0,0.00,-66.67,-60.00,-25.00,0.00,-20.00,-25.00
2202,흥아해운(주),3280,배당금(*)(IFRS)(천원),486594.0,486594.0,751621.0,751621.0,584594.0,632567.0,0.0,0.0,0.0,0.0,-54.47,0.00,22.22,-8.21,100.00,NaN,NaN

In [24]:
df.drop(df.iloc[:,3:12],inplace=True,axis=1)
df

,회사,거래소코드,년도,2012년 감소율,2013년 감소율,2014년 감소율,2015년 감소율,2016년 감소율,2017년 감소율,2018년 감소율,2019년 감소율
0,(주)CMG제약,58820,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)DB하이텍,990,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,-inf,0.98,-40.05
2,(주)ES큐브,50120,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)HJ중공업,97230,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)MH에탄올,23150,배당금(*)(IFRS)(천원),NaN,NaN,-inf,-23.31,-18.85,-11.67,2.77,2.98
...,...,...,...,...,...,...,...,...,...,...,...
2198,휴림로봇(주),90710,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2199,휴마시스(주),205470,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2200,휴젤(주),145020,배당금(*)(IFRS)(천원),NaN,-inf,0.00,100.00,NaN,NaN,NaN,NaN
2201,흥구석유(주),24060,배당금(*)(IFRS)(천원),40.0,0.00,-66.67,-60.00,-25.00,0.00,-20.00,-25.00
2202,흥아해운(주),3280,배당금(*)(IFRS)(천원),0.0,-54.47,0.00,22.22,-8.21,100.00,NaN,NaN

In [25]:
for i in range(0, len(df)):
    for year in range(2011, 2018):
        if year != 2019:
            if df.iloc[i][str(year+1)+"년 감소율"] < -20:
                df.loc[i, str(year+1)+"년 감소율여부"] = 1
            else:
                    df.loc[i, str(year+1)+"년 감소율여부"] = 0

In [26]:
df

,회사,거래소코드,년도,2012년 감소율,2013년 감소율,2014년 감소율,2015년 감소율,2016년 감소율,2017년 감소율,2018년 감소율,2019년 감소율,2012년 감소율여부,2013년 감소율여부,2014년 감소율여부,2015년 감소율여부,2016년 감소율여부,2017년 감소율여부,2018년 감소율여부
0,(주)CMG제약,58820,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,(주)DB하이텍,990,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,-inf,0.98,-40.05,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,(주)ES큐브,50120,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,(주)HJ중공업,97230,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,(주)MH에탄올,23150,배당금(*)(IFRS)(천원),NaN,NaN,-inf,-23.31,-18.85,-11.67,2.77,2.98,0.0,0.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2198,휴림로봇(주),90710,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2199,휴마시스(주),205470,배당금(*)(IFRS)(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2200,휴젤(주),145020,배당금(*)(IFRS)(천원),NaN,-inf,0.00,100.00,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2201,흥구석유(주),24060,배당금(*)(IFRS)(천원),40.0,0.00,-66.67,-60.00,-25.00,0.00,-20.00,-25.00,0.0,0.0,1.0,1.0,1.0,0.0,0.0
2202,흥아해운(주),3280,배당금(*)(IFRS)(천원),0.0,-54.47,0.00,22.22,-8.21,100.00,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.drop(df.iloc[:,3:12],inplace=True,axis=1)