In [2]:
import pandas as pd

## 데이터 불러오기

In [52]:
#총자산대비자본율dataframe
df = pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/재무적 범주의 전략/총자산대비자본/총자산대비자본율.csv',encoding='cp949')
# df_ = df.drop(['Unnamed: 8','Unnamed: 9'],axis=1)
df_

,회사명,거래소코드,회계년도,자산(*)(IFRS)(천원),자본(*)(IFRS)(천원),자산(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),자본율(개별)
0,(주)CMG제약,58820,10-Dec,"26,776","18,405","26,776","18,405",NaN
1,(주)CMG제약,58820,11-Dec,"27,549","18,291","27,305","18,034",NaN
2,(주)CMG제약,58820,12-Dec,"56,989","31,603","57,108","31,591",NaN
3,(주)CMG제약,58820,13-Dec,"55,962","49,048","55,913","48,997",NaN
4,(주)CMG제약,58820,14-Dec,"58,127","49,067","58,068","49,003",NaN
...,...,...,...,...,...,...,...,...
19484,흥아해운(주),3280,15-Dec,"771,212","161,825","791,641","173,077",NaN
19485,흥아해운(주),3280,16-Dec,"942,587","183,829","958,532","192,487",NaN
19486,흥아해운(주),3280,17-Dec,"834,107","107,615","848,959","116,884",NaN
19487,흥아해운(주),3280,18-Dec,"782,787","56,732","803,698","73,148",NaN
19488,흥아해운(주),3280,19-Dec,"386,551","17,632","430,963","30,919",NaN

In [54]:
#2년 연속 한계기업
df1=pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/전체데이터/전체데이터_2년연속성한계기업.csv',encoding='cp949')
# df1_ = df1.drop(['Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 10'],axis=1)
df1_

,회사명,거래소코드,회계년도,이자보상배율(이자비용)(IFRS),이자보상배율(이자비용)(IFRS연결),이자보상배율
0,(주)CMG제약,58820,11-Dec,3.94,3.53,3.53
1,(주)CMG제약,58820,12-Dec,-7.45,-7.75,-7.75
2,(주)CMG제약,58820,13-Dec,0.73,0.70,0.70
3,(주)CMG제약,58820,14-Dec,3.63,3.60,3.60
4,(주)CMG제약,58820,15-Dec,-32.20,-32.22,-32.22
...,...,...,...,...,...,...
6464,흥아해운(주),3280,14-Dec,0.96,1.12,1.12
6465,흥아해운(주),3280,15-Dec,0.79,1.02,1.02
6466,흥아해운(주),3280,16-Dec,0.04,0.21,0.21
6467,흥아해운(주),3280,17-Dec,-0.61,-0.42,-0.42
6468,흥아해운(주),3280,18-Dec,-1.26,-1.16,-1.16

## 데이터 합치기 (MERGE) 합집합 안에 작은 집합(단순 합치기)

In [55]:
df2 = pd.merge(df_, df1_)
df2

,회사명,거래소코드,회계년도,자산(*)(IFRS)(천원),자본(*)(IFRS)(천원),자산(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),자본율(개별),이자보상배율(이자비용)(IFRS),이자보상배율(이자비용)(IFRS연결),이자보상배율
0,(주)CMG제약,58820,11-Dec,"27,549","18,291","27,305","18,034",NaN,3.94,3.53,3.53
1,(주)CMG제약,58820,12-Dec,"56,989","31,603","57,108","31,591",NaN,-7.45,-7.75,-7.75
2,(주)CMG제약,58820,13-Dec,"55,962","49,048","55,913","48,997",NaN,0.73,0.70,0.70
3,(주)CMG제약,58820,14-Dec,"58,127","49,067","58,068","49,003",NaN,3.63,3.60,3.60
4,(주)CMG제약,58820,15-Dec,"56,592","46,873","56,533","46,807",NaN,-32.20,-32.22,-32.22
...,...,...,...,...,...,...,...,...,...,...,...
6452,흥아해운(주),3280,14-Dec,"627,805","153,936","649,240","167,403",NaN,0.96,1.12,1.12
6453,흥아해운(주),3280,15-Dec,"771,212","161,825","791,641","173,077",NaN,0.79,1.02,1.02
6454,흥아해운(주),3280,16-Dec,"942,587","183,829","958,532","192,487",NaN,0.04,0.21,0.21
6455,흥아해운(주),3280,17-Dec,"834,107","107,615","848,959","116,884",NaN,-0.61,-0.42,-0.42
6456,흥아해운(주),3280,18-Dec,"782,787","56,732","803,698","73,148",NaN,-1.26,-1.16,-1.16

In [56]:
df2.to_csv("2년연속한계기업_총자본율.csv",encoding='CP949')

## 데이터프레임 합치기(left기준)

In [22]:
df = pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/재무적 범주의 전략/총자산대비자본/총자산대비자본율.csv',encoding='cp949')
df.rename(columns={'Unnamed: 0':'회사명'},inplace=True)

,Unnamed: 0,거래소코드,회계년도,자산(*)(IFRS)(천원),자본(*)(IFRS)(천원),자산(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),자본율(연결),자본율
0,(주)CMG제약,58820,10-Dec,"26,776","18,405","26,776","18,405",68.74,68.74
1,(주)CMG제약,58820,11-Dec,"27,549","18,291","27,305","18,034",66.39,66.05
2,(주)CMG제약,58820,12-Dec,"56,989","31,603","57,108","31,591",55.45,55.32
3,(주)CMG제약,58820,13-Dec,"55,962","49,048","55,913","48,997",87.65,87.63
4,(주)CMG제약,58820,14-Dec,"58,127","49,067","58,068","49,003",84.41,84.39
...,...,...,...,...,...,...,...,...,...
19487,흥아해운(주),3280,15-Dec,"771,212","161,825","791,641","173,077",NaN,NaN
19488,흥아해운(주),3280,16-Dec,"942,587","183,829","958,532","192,487",NaN,NaN
19489,흥아해운(주),3280,17-Dec,"834,107","107,615","848,959","116,884",NaN,NaN
19490,흥아해운(주),3280,18-Dec,"782,787","56,732","803,698","73,148",NaN,NaN
19491,흥아해운(주),3280,19-Dec,"386,551","17,632","430,963","30,919",NaN,NaN

In [24]:
df1=pd.read_csv("C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/재무적 범주의 전략/총자산대비자본/2년연속한계기업_총자본율_개별연결결합.csv",encoding='cp949')
df1 = df1.drop(['Unnamed: 0'],axis=1)

,Unnamed: 0,회사명,거래소코드,회계년도,자산(*)(IFRS)(천원),자본(*)(IFRS)(천원),자본율(개별),자산(*)(IFRS)(천원)(연결),자본(*)(IFRS)(천원)(연결),자본율(연결),자본율
0,0,(주)CMG제약,58820,11-Dec,"27,549","18,291",66.39,"38,200","14,702",66.39,66.39
1,1,(주)CMG제약,58820,12-Dec,"56,989","31,603",55.45,"52,992","28,102",55.45,55.45
2,2,(주)CMG제약,58820,13-Dec,"55,962","49,048",87.65,"55,913","48,997",87.63,87.63
3,3,(주)CMG제약,58820,14-Dec,"58,127","49,067",84.41,"58,068","49,003",84.39,84.39
4,4,(주)CMG제약,58820,15-Dec,"56,592","46,873",82.83,"56,533","46,807",82.80,82.80
...,...,...,...,...,...,...,...,...,...,...,...
6370,6446,흥아해운(주),3280,14-Dec,"627,805","153,936",24.52,"649,240","167,403",25.78,25.78
6371,6447,흥아해운(주),3280,15-Dec,"771,212","161,825",20.98,"791,641","173,077",21.86,21.86
6372,6448,흥아해운(주),3280,16-Dec,"942,587","183,829",19.50,"958,532","192,487",20.08,20.08
6373,6449,흥아해운(주),3280,17-Dec,"834,107","107,615",12.90,"848,959","116,884",13.77,13.77
6374,6450,흥아해운(주),3280,18-Dec,"782,787","56,732",7.25,"803,698","73,148",9.10,9.10

In [27]:
df_OUTER_JOIN = pd.merge(df1,df, on=['회사명','회계년도'],how='outer')
df_OUTER_JOIN

,회사명,거래소코드_x,회계년도,자산(*)(IFRS)(천원)_x,자본(*)(IFRS)(천원)_x,자본율(개별),자산(*)(IFRS)(천원)(연결),자본(*)(IFRS)(천원)(연결),자본율(연결)_x,자본율_x,거래소코드_y,자산(*)(IFRS)(천원)_y,자본(*)(IFRS)(천원)_y,자산(*)(IFRS연결)(천원),자본(*)(IFRS연결)(천원),자본율(연결)_y,자본율_y
0,(주)CMG제약,58820.0,11-Dec,"27,549","18,291",66.39,"38,200","14,702",66.39,66.39,58820,"27,549","18,291","27,305","18,034",66.39,66.05
1,(주)CMG제약,58820.0,12-Dec,"56,989","31,603",55.45,"52,992","28,102",55.45,55.45,58820,"56,989","31,603","57,108","31,591",55.45,55.32
2,(주)CMG제약,58820.0,13-Dec,"55,962","49,048",87.65,"55,913","48,997",87.63,87.63,58820,"55,962","49,048","55,913","48,997",87.65,87.63
3,(주)CMG제약,58820.0,14-Dec,"58,127","49,067",84.41,"58,068","49,003",84.39,84.39,58820,"58,127","49,067","58,068","49,003",84.41,84.39
4,(주)CMG제약,58820.0,15-Dec,"56,592","46,873",82.83,"56,533","46,807",82.80,82.80,58820,"56,592","46,873","56,533","46,807",82.83,82.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19487,흥구석유(주),NaN,17-Dec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24060,"79,912","69,754",NaN,NaN,NaN,NaN
19488,흥구석유(주),NaN,18-Dec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24060,"75,206","70,442",NaN,NaN,NaN,NaN
19489,흥구석유(주),NaN,19-Dec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24060,"83,661","77,001",NaN,NaN,NaN,NaN
19490,흥아해운(주),NaN,10-Dec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3280,"540,999","132,208","548,093","136,776",NaN,NaN
19491,흥아해운(주),NaN,19-Dec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3280,"386,551","17,632","430,963","30,919",NaN,NaN

## 데이터 프레임 column기준별로 오름차순 정렬

In [32]:
df3=pd.read_csv("C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/재무적 범주의 전략/총자산대비자본/2년연속한계기업_총자본율_개별연결결합.csv",encoding='cp949')
df3 = df3.drop(['Unnamed: 0'],axis=1)
dfdf3.sort_values(['회사명','회계년도'],ascending=True, inplace=True)

,회사명,거래소코드,회계년도,자산(*)(IFRS)(천원),자본(*)(IFRS)(천원),자산(*)(IFRS)(천원)(연결),자본(*)(IFRS)(천원)(연결),자본율(연결),자본율
0,(주)CMG제약,58820,11-Dec,"27,549","18,291","38,200","14,702",66.39,66.39
1,(주)CMG제약,58820,12-Dec,"56,989","31,603","52,992","28,102",55.45,55.45
2,(주)CMG제약,58820,13-Dec,"55,962","49,048","55,913","48,997",87.63,87.63
3,(주)CMG제약,58820,14-Dec,"58,127","49,067","58,068","49,003",84.39,84.39
4,(주)CMG제약,58820,15-Dec,"56,592","46,873","56,533","46,807",82.8,82.8
...,...,...,...,...,...,...,...,...,...
8020,효성아이티엑스(주),94280,10-Dec,"61,793","21,101","58,569","17,877",34.15,171515.77
8021,휴림네트웍스(주),192410,10-Dec,NaN,NaN,NaN,NaN,#DIV/0!,#DIV/0!
8022,휴림로봇(주),90710,10-Dec,"39,485","17,771","39,696","17,865",45.01,88199.68
8023,흥구석유(주),24060,10-Dec,"77,084","62,050",NaN,NaN,80.50,0.00
8024,흥아해운(주),3280,10-Dec,"540,999","132,208","548,093","136,776",24.44,2242812.57

In [35]:
df3.to_csv("전체데이터_2011_KOSPI+KOSDAQ_자본율.csv",encoding='CP949')