In [53]:
import pandas as pd
import numpy as np

## 데이터 불러오기

In [54]:
df=pd.read_csv('C:/Users/user/Desktop/프로젝트2/데이터/data/회생전략/재무적 범주의 전략/총자산대비자본/2년연속한계기업_총자본율_개별연결결합2.csv',encoding='CP949')
df

,Unnamed: 0,회사명,거래소코드,회계년도,자산(*)(IFRS)(천원),자본(*)(IFRS)(천원),자본율(개별),자산(*)(IFRS)(천원)(연결),자본(*)(IFRS)(천원)(연결),자본율(연결),자본율
0,0,(주)CMG제약,58820,11-Dec,"27,549","18,291",66.39,"38,200","14,702",66.39,66.39
1,1,(주)CMG제약,58820,12-Dec,"56,989","31,603",55.45,"52,992","28,102",55.45,55.45
2,2,(주)CMG제약,58820,13-Dec,"55,962","49,048",87.65,"55,913","48,997",87.63,87.63
3,3,(주)CMG제약,58820,14-Dec,"58,127","49,067",84.41,"58,068","49,003",84.39,84.39
4,4,(주)CMG제약,58820,15-Dec,"56,592","46,873",82.83,"56,533","46,807",82.80,82.80
...,...,...,...,...,...,...,...,...,...,...,...
6370,6446,흥아해운(주),3280,14-Dec,"627,805","153,936",24.52,"649,240","167,403",25.78,25.78
6371,6447,흥아해운(주),3280,15-Dec,"771,212","161,825",20.98,"791,641","173,077",21.86,21.86
6372,6448,흥아해운(주),3280,16-Dec,"942,587","183,829",19.50,"958,532","192,487",20.08,20.08
6373,6449,흥아해운(주),3280,17-Dec,"834,107","107,615",12.90,"848,959","116,884",13.77,13.77
6374,6450,흥아해운(주),3280,18-Dec,"782,787","56,732",7.25,"803,698","73,148",9.10,9.10

In [55]:
df

,Unnamed: 0,회사명,거래소코드,회계년도,자산(*)(IFRS)(천원),자본(*)(IFRS)(천원),자본율(개별),자산(*)(IFRS)(천원)(연결),자본(*)(IFRS)(천원)(연결),자본율(연결),자본율
0,0,(주)CMG제약,58820,11-Dec,"27,549","18,291",66.39,"38,200","14,702",66.39,66.39
1,1,(주)CMG제약,58820,12-Dec,"56,989","31,603",55.45,"52,992","28,102",55.45,55.45
2,2,(주)CMG제약,58820,13-Dec,"55,962","49,048",87.65,"55,913","48,997",87.63,87.63
3,3,(주)CMG제약,58820,14-Dec,"58,127","49,067",84.41,"58,068","49,003",84.39,84.39
4,4,(주)CMG제약,58820,15-Dec,"56,592","46,873",82.83,"56,533","46,807",82.80,82.80
...,...,...,...,...,...,...,...,...,...,...,...
6370,6446,흥아해운(주),3280,14-Dec,"627,805","153,936",24.52,"649,240","167,403",25.78,25.78
6371,6447,흥아해운(주),3280,15-Dec,"771,212","161,825",20.98,"791,641","173,077",21.86,21.86
6372,6448,흥아해운(주),3280,16-Dec,"942,587","183,829",19.50,"958,532","192,487",20.08,20.08
6373,6449,흥아해운(주),3280,17-Dec,"834,107","107,615",12.90,"848,959","116,884",13.77,13.77
6374,6450,흥아해운(주),3280,18-Dec,"782,787","56,732",7.25,"803,698","73,148",9.10,9.10

## 해당 행,열 데이터 값 찾기

In [56]:
df.iloc[1][9]

55.45

## 데이터프레임 결측치 갯수 확인

In [57]:
df.isna().sum()

Unnamed: 0               0
회사명                      0
거래소코드                    0
회계년도                     0
자산(*)(IFRS)(천원)          6
자본(*)(IFRS)(천원)          6
자본율(개별)                  6
자산(*)(IFRS)(천원)(연결)    250
자본(*)(IFRS)(천원)(연결)    250
자본율(연결)                 75
자본율                      6
dtype: int64

## 결측치 찾기

In [59]:
df[df['자본율'].isnull()]

,Unnamed: 0,회사명,거래소코드,회계년도,자산(*)(IFRS)(천원),자본(*)(IFRS)(천원),자본율(개별),자산(*)(IFRS)(천원)(연결),자본(*)(IFRS)(천원)(연결),자본율(연결),자본율
4161,4223,글로본(주),19660,11-Mar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4162,4224,글로본(주),19660,12-Mar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4163,4225,글로본(주),19660,13-Mar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4164,4226,글로본(주),19660,14-Mar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4165,4227,글로본(주),19660,15-Mar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4166,4228,글로본(주),19660,16-Mar,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 연결,개별 결측치 합치기

In [50]:
for i in range(0,len(df)):
    if pd.isna(df.iloc[i][9]):
        df.loc[i,"자본율"]=df.iloc[i][8]

In [52]:
df.isna().sum()

Unnamed: 0               0
회사명                      0
거래소코드                    0
회계년도                     0
자산(*)(IFRS)(천원)          6
자본(*)(IFRS)(천원)          6
자본율(개별)                  6
자산(*)(IFRS)(천원)(연결)    250
자본(*)(IFRS)(천원)(연결)    250
자본율(연결)                 75
자본율                     75
dtype: int64

## 연결,개별 결측치 합치기2

In [ ]:
# df.iloc[i][5]
# df.iloc[i][8]

# csv 한바퀴 돌립니다
for i in range(0,len(df)):
    # 컬럼들 순회합니다
        # 개별에 결측치가 없다면
        if not pd.isna(df.iloc[i][5]):
            # 연결에도 결측치가 없다면
            if not pd.isna(df.iloc[i][8]):
                # 연결삽입
                df.loc[i, "자본율"] = df.iloc[i][8]

            # 연결이 결측치라면
            else:
                #개별 값 삽입
                df.loc[i, "자본율"] = df.iloc[i][5]

        # 개별에 결측치가 있다면
        else:
            # 연결에 결측치가 없다면
            if not pd.isna(df.iloc[i][8]):
                # 연결 삽입
                df.loc[i, "자본율"] = df.iloc[i][8]

            # 둘 다 없으면 통과
            else:
                pass

In [35]:
df = df.drop(['Unnamed: 0'],axis=1)

In [30]:
df["자본율(연결)"].value_counts()

#DIV/0!    256
33.7         6
42.92        6
83.8         5
43.45        5
          ...
55.63        1
37.13        1
83.51        1
60.01        1
9.1          1
Name: 자본율(연결), Length: 4283, dtype: int64

## 결측치 None값으로 대체

In [31]:
df = df.replace("#DIV/0!", None)

In [32]:
# df.iloc[i][5]
# df.iloc[i][8]

# csv 한바퀴 돌립니다
for i in range(0,len(df)):
    # 컬럼들 순회합니다
        # 개별에 결측치가 없다면
        if not pd.isna(df.iloc[i][5]):
            # 연결에도 결측치가 없다면
            if not pd.isna(df.iloc[i][8]):
                # 연결삽입
                df.loc[i, "자본율"] = df.iloc[i][8]

            # 연결이 결측치라면
            else:
                #개별 값 삽입
                df.loc[i, "자본율"] = df.iloc[i][5]

        # 개별에 결측치가 있다면
        else:
            # 연결에 결측치가 없다면
            if not pd.isna(df.iloc[i][8]):
                # 연결 삽입
                df.loc[i, "자본율"] = df.iloc[i][8]

            # 둘 다 없으면 통과
            else:
                pass

In [33]:
df.to_csv("2년연속한계기업_총자본율_개별연결결합2.csv",encoding="CP949")